os:
  - linux
  - osx

language: c

env:
  - BRANCH=0.19.0
  - BRANCH=0.19.2
  - BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim/toolchains/nim-0.19.0"
    - "$HOME/.choosenim/toolchains/nim-0.19.2"

install:
  - export CHOOSENIM_CHOOSE_VERSION=$BRANCH
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH

script:
  - nimble install -y
  - nimble test
  - nimble --nimbleDir:`pwd`/test install nimterop -y